# author 13
# qq-group 791509631
# email 2449207463@qq.com
# link https://github.com/newbee-ltd

# 服务器配置
server:
  port: 28079
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 16
      worker: 256

# 项目全局配置
project:
  name: newbee-mall-plus # 项目名称
  #  fileUploadPath: /opt/newbee-mall-plus/upload/  # 上传文件的默认url前缀，根据部署设置自行修改，linux下路径
  fileUploadPath: D:\\upload\\              # 上传文件的默认url前缀，根据部署设置自行修改，windows下路径
  orderUnpaidOverTime: 300 # 订单未支付超期时间，单位秒
  serverUrl: http://localhost:28079 # 服务器地址

# spring配置
spring:
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: @activatedProperties@

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml    # mapper映射文件位置

# alipay 需要自行申请支付宝的沙箱账号、申请appID，并依次配置AppID、密钥、公钥，否则无法发起支付宝支付。
alipay:
  app-id: 2021000121631406
  rsa-private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCFxI9n34WxRYhNsTRzh4aMTCUsyEOjK/Gs3SuUZ2TM1RcUWoT7lHZ9UyhGu//prjXGcUtb56zVEHEvcPo0Z733ojdyzWr/GFSkcEeA/GKEM080+q8A1MnkZ7yU/nd8CNB9OfMz1z+RG8VKOf9GsrOh9cyEsgkS7bgH+jBV3s97WgNUuZlDxw8TOFRQnBfngsGHkl4dbQnwaPufRM+361EqjZ0P9YAMTCoYmvURtQ3CrT/T8PBw8MsicTgPzBYcs7G5PO9zzbDYGLkztRQ993SLnukBHyZyxcGXgaMAZ/n3fipCPYeKJT5sH50VV/VM37XzPcItI18dpBCvI3ll3h5jAgMBAAECggEALsg3fxRlJUI0ETfQKDdVjutydN71CLPtqY8QFq6yShCcKboel/2sEthqVZKaRZdvpx8oQ9QaVcmSTA0u8/T0Mw7AZZ4BtYVE1N2PpESgD6wCH30shxXkJcVB5rm3/+D1SVZi/9ZfnNghf3wZExicSiA0jpPVKJGKsv+EuANcfL7TNKdWRC9SBt9NjyTi13KV5NmrN5H/fQ4sLJVGMdzevZaSaOqM89iQ+xe8x9Vcig+WnLOeui16VISsbBkBdRFIDvaIcEiUUWuxEnF/k8pnmgvLYgC+ia9i6Z1xoFbgPZz+gael9c5MOX0UUluDQyFG53jzczaTn2UlOzTZzpJqAQKBgQDYaDOcfEQiV7lvRBS7/6AOxt82NO3k41TZqJCxfJW3ga44GhnltY/i0pCZB/8Hvqu+1VIbg1V6EXNx0kL8c8+x9rdeAza8cky8lbOb2/Qg7NC8eMgPejotxQkjqlR2D7XWPmg7AdO8h88l/q9HCAI/qHSFvIxJsw2KW8Q7gG/cgwKBgQCePc6wbnPBJc/6mcVCZDTBUuNoDPv7sM1C0LY7SBPrCLDAYCJOUPSEh55U5PZmKtQxmaALXpfIEGCAFrH2YuVIOTMwrq306VOCZsGPMs/SGKWL5e/4BvRWsVD3dAEaD07Zhn1g7wc7Nwq0No9riVlfrVhwOAGbYY38AFaydx7QoQKBgDa6c4L5skl1IgJPl2bMCPBzvvN4g0lFbKn3BVC9jydvdl3dy/rZ5d+ZHNR2vzp4L/r8+9zVZAKQ8z8vy50ItNfu6wStj2QtC9cNjPS3tY+2FDv117KCWMBGej84zk9lPblG4xk5JxEgz3RuamluTxNGSOGhg2EIFT6OYpwhqSh9AoGADDexcaXVgiAtQqgEtu+Nsy93J115RyGLd5EtwL3767WsD+5cN7fAaUsfSmazL4g3Ae1ekgInrea1zK3z55YTJdRkw2l5POOW8waEA05lBU+p2HdUY84Fp3vhSHnIa/6qk9jybT2HTWceiHN990uPfvefUGrClQCfOcm85+KSmoECgYB1k8mQ/La7JmA50Sy1qwMjp/E9JnGzTHW6IjQ6Qf1+irsFcnYD9tmyLu+Vr4dQUqk39qHgV6JO15mLLkT1JPMFQ+nU2kb2rJa7q/qDJ2nrmvDmqRkJ6gyRM6coS+uXNtHHXM+y7RDeUnP00YtppT6lVq9auu5jzm2Pen7CXS9f2w==
  alipay-public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkZqYjN9aQq+sp9KSWO5DZGIJeO/cfIkb7IGeHewFEVLOunfJn04D/0NOCpKlusMAznx0Jyj7iC+6j+d0iZMVVI1kzK2CHDcYO7Brv7uqFjGrE1OAZTJALzoh8BwGG5VoJnT0E0GwbolkNkgcMFKeAqQswZsFe5SE9EQa4ed9e1axXUFkYRANQ6m7t1rt4MHPwBtJ2RIwwAMBkgybu/6FTwVaIvRj8NVPRzTQT8DmNvyVNBKi4RFrZSQUmAAOf+b0oCRC2AP5PFu8hzyRIaQtRLd74iLAYS3+f65Z+e8f7Dpk8w2VASwgj//no6f0ZvsR8srLt6UtK/vJd4XiTjqlJwIDAQAB
  gateway: https://openapi.alipaydev.com/gateway.do
  charset: UTF-8
  format: json
  #  log-path: /opt/newbee-mall-plus/log
  log-path: D://newbee-mall-plus//log
  signtype: RSA2
